### ISSUE TITLE
Secrets required

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/community-hub-extension-example#1]
Hi @berndruecker 

this repository is an example using current HUB Maven parent and latest GH action and should be used to really test the CI/CD (and release a dummy artifact into OSS Maven Central).

Since we had some problems in the past with the release, I would use this artifact to test the entire tool stack. This can also be used as a reference for new Camunda HUB contributors. A reference / example is much better than README explaining how to set it up in theory.

Currently, this repository is missing the Camunda secrets - please make sure to set them up / allow the ORG secretes to be used.

Cheers,

Simon

**Comment by zambrovski** [comment]
@camunda-community-hub/devrel could you please supply the GH secrets?

**Comment by xomiamoore** [comment]
Hi @zambrovski, this repo should have access now!
